package:
  name: qtawesome
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG') }}

build:
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - qtpy

test:
  imports:
    - qtawesome
  requires:
    - pyqt

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  summary: Iconic fonts in PyQt and PySide applications
